/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.Transport;

import Healthplus.E_System;
import Healthplus.EmergencyServices.EmergencyRequestDirectory;
import Healthplus.Enterprises.Enterprise;
import Healthplus.Org.Org;
import Healthplus.UserAccount.UserAccount;
import UI.EmergencyServices.EmergencyServicesHome_Panel;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author sampadadhole
 */
public class DriverWorkAreaPage extends javax.swing.JPanel {

      private JPanel userProcessContainer;
    private UserAccount userAccount;
    private Org organization;
    private Enterprise enterprise;
    private E_System system;
    private EmergencyRequestDirectory EmergencyList;
    private EmergencyServicesHome_Panel emerhome;
    public DriverWorkAreaPage(JPanel userProcessContainer, E_System system, UserAccount userAccount, Org organization, Enterprise enterprise, EmergencyRequestDirectory EmergencyList) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.organization = organization;
         this.EmergencyList=EmergencyList;
        this.enterprise = enterprise;
        this.system = system;
        
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel16 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        btn_callEmergency = new javax.swing.JButton();
        lblHeader = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jPanel17.setBackground(new java.awt.Color(255, 232, 215));
        jPanel17.setMaximumSize(new java.awt.Dimension(700, 700));
        jPanel17.setMinimumSize(new java.awt.Dimension(700, 700));
        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_callEmergency.setBackground(new java.awt.Color(255, 255, 255));
        btn_callEmergency.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        btn_callEmergency.setText("View Emergencies");
        btn_callEmergency.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_callEmergencyActionPerformed(evt);
            }
        });
        jPanel17.add(btn_callEmergency, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 200, 30));

        lblHeader.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        lblHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeader.setText("Driver's Work Area");
        jPanel17.add(lblHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 270, 26));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ambulance-ambulanceemoji.gif"))); // NOI18N
        jPanel17.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 550, 490));

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1083, Short.MAX_VALUE)
            .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel16Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, 1083, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 975, Short.MAX_VALUE)
            .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel16Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, 975, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1083, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 975, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_callEmergencyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_callEmergencyActionPerformed
        // TODO add your handling code here:
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        DriverViewDetailsAreaPanel mtsj = new DriverViewDetailsAreaPanel(userProcessContainer, system, userAccount, organization, enterprise,EmergencyList);
        userProcessContainer.add("mtsj", mtsj);
        cardLayout.next(userProcessContainer);
    }//GEN-LAST:event_btn_callEmergencyActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_callEmergency;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JLabel lblHeader;
    // End of variables declaration//GEN-END:variables
}
