/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.ApplicantWorkArea;

import Healthplus.DB4OUtil.DB4OUtil;
import Healthplus.E_System;
import Healthplus.UserAccount.UserAccount;
import UI.GuestWorkArea.ApplyForJobJPanel;
import UI.GuestWorkArea.RaiseIssueJPanel;
import java.awt.CardLayout;
import javax.swing.JPanel;


public class ApplicantWorkArea_Page extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    private JPanel userProcessContainer;
    private E_System system;
    private UserAccount userAccount;
    private DB4OUtil dB4OUtil;

    public ApplicantWorkArea_Page(JPanel userProcessContainer, E_System system, UserAccount userAccount, DB4OUtil dB4OUtil) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        this.userAccount = userAccount;
        this.dB4OUtil = dB4OUtil;
        populateForm();
    }

    public void populateForm() {
        lblName.setText(userAccount.getApplicant().getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHeader = new javax.swing.JLabel();
        lblHi = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        btn_viewpostedjobs = new javax.swing.JButton();
        btn_raiserequest = new javax.swing.JButton();
        btn_viewApplStatus = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 217, 198));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblHeader.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        lblHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeader.setText("Applicant Work Area");
        add(lblHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 19, 670, 26));

        lblHi.setFont(new java.awt.Font("Comic Sans MS", 1, 16)); // NOI18N
        lblHi.setText("Welcome,");
        add(lblHi, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 90, 30));

        lblName.setFont(new java.awt.Font("Comic Sans MS", 1, 16)); // NOI18N
        lblName.setText("Applicant");
        add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 150, 22));

        btn_viewpostedjobs.setBackground(new java.awt.Color(255, 255, 255));
        btn_viewpostedjobs.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        btn_viewpostedjobs.setText("View Jobs");
        btn_viewpostedjobs.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_viewpostedjobs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_viewpostedjobsActionPerformed(evt);
            }
        });
        add(btn_viewpostedjobs, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, 217, 30));

        btn_raiserequest.setBackground(new java.awt.Color(255, 255, 255));
        btn_raiserequest.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        btn_raiserequest.setText("Raise A Request");
        btn_raiserequest.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_raiserequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_raiserequestActionPerformed(evt);
            }
        });
        add(btn_raiserequest, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, 217, 30));

        btn_viewApplStatus.setBackground(new java.awt.Color(255, 255, 255));
        btn_viewApplStatus.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        btn_viewApplStatus.setText("View Application Status");
        btn_viewApplStatus.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_viewApplStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_viewApplStatusActionPerformed(evt);
            }
        });
        add(btn_viewApplStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, 217, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ApplicantWork.gif"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 730, 360));
    }// </editor-fold>//GEN-END:initComponents

    private void btn_viewpostedjobsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_viewpostedjobsActionPerformed
        // TODO add your handling code here:
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        ApplyForJobJPanel afjp = new ApplyForJobJPanel(userProcessContainer, system, dB4OUtil, userAccount, "A");
        userProcessContainer.add("afjp", afjp);
        cardLayout.next(userProcessContainer);
    }//GEN-LAST:event_btn_viewpostedjobsActionPerformed

    private void btn_raiserequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_raiserequestActionPerformed
//        // TODO add your handling code here:
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        RaiseIssueJPanel rijp = new RaiseIssueJPanel(userProcessContainer, userAccount, system);
        userProcessContainer.add("rijp", rijp);
        cardLayout.next(userProcessContainer);
    }//GEN-LAST:event_btn_raiserequestActionPerformed

    private void btn_viewApplStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_viewApplStatusActionPerformed
        // TODO add your handling code here:
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        ApplicationStatus_Page asjp = new ApplicationStatus_Page(userProcessContainer, system, userAccount);
        userProcessContainer.add("asjp", asjp);
        cardLayout.next(userProcessContainer);
    }//GEN-LAST:event_btn_viewApplStatusActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_raiserequest;
    private javax.swing.JButton btn_viewApplStatus;
    private javax.swing.JButton btn_viewpostedjobs;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JLabel lblHi;
    private javax.swing.JLabel lblName;
    // End of variables declaration//GEN-END:variables
}
