/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.GuestWorkArea;

import Healthplus.DB4OUtil.DB4OUtil;
import Healthplus.E_System;
import Healthplus.EmergencyServices.Emergency;
import Healthplus.EmergencyServices.EmergencyRequestDirectory;
import Healthplus.Enterprises.EmergencyServices;
import Healthplus.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JPanel;

public class GuestWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private E_System system;
    private DB4OUtil dB4OUtil;
    private EmergencyRequestDirectory EmergencyList;
    private RaiseEmergencyServices raise;
    ArrayList<Emergency> emergency;

    /**
     * Creates new form GuestWorkAreaJPanel
     */
    public GuestWorkAreaJPanel(JPanel userProcessContainer, E_System system, DB4OUtil dB4OUtil) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        this.dB4OUtil = dB4OUtil;
        //this.raise = new RaiseEmergencyServices();
        EmergencyList = new EmergencyRequestDirectory();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHeader = new javax.swing.JLabel();
        btn_trusts = new javax.swing.JButton();
        btn_viewjobs = new javax.swing.JButton();
        btn_addfundraisers = new javax.swing.JButton();
        btn_raiserequest = new javax.swing.JButton();
        btn_logout = new javax.swing.JButton();
        btn_oldagehome = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 219, 207));
        setMaximumSize(new java.awt.Dimension(700, 700));
        setMinimumSize(new java.awt.Dimension(700, 700));
        setPreferredSize(new java.awt.Dimension(700, 700));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblHeader.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        lblHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeader.setText("Facilities for Guest");
        add(lblHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 250, 27));

        btn_trusts.setBackground(new java.awt.Color(255, 255, 255));
        btn_trusts.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        btn_trusts.setForeground(new java.awt.Color(0, 0, 0));
        btn_trusts.setText("Trusts");
        btn_trusts.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_trusts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_trustsActionPerformed(evt);
            }
        });
        add(btn_trusts, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 251, -1));

        btn_viewjobs.setBackground(new java.awt.Color(255, 255, 255));
        btn_viewjobs.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        btn_viewjobs.setForeground(new java.awt.Color(0, 0, 0));
        btn_viewjobs.setText("Jobs");
        btn_viewjobs.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_viewjobs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_viewjobsActionPerformed(evt);
            }
        });
        add(btn_viewjobs, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 251, -1));

        btn_addfundraisers.setBackground(new java.awt.Color(255, 255, 255));
        btn_addfundraisers.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        btn_addfundraisers.setForeground(new java.awt.Color(0, 0, 0));
        btn_addfundraisers.setText("Sign up as fundraising company");
        btn_addfundraisers.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_addfundraisers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addfundraisersActionPerformed(evt);
            }
        });
        add(btn_addfundraisers, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 251, -1));

        btn_raiserequest.setBackground(new java.awt.Color(255, 255, 255));
        btn_raiserequest.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        btn_raiserequest.setForeground(new java.awt.Color(0, 0, 0));
        btn_raiserequest.setText("Raise A Request");
        btn_raiserequest.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_raiserequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_raiserequestActionPerformed(evt);
            }
        });
        add(btn_raiserequest, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, 251, -1));

        btn_logout.setBackground(new java.awt.Color(255, 255, 255));
        btn_logout.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        btn_logout.setForeground(new java.awt.Color(0, 0, 0));
        btn_logout.setText("Logout");
        btn_logout.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });
        add(btn_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, -1));

        btn_oldagehome.setBackground(new java.awt.Color(255, 255, 255));
        btn_oldagehome.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        btn_oldagehome.setForeground(new java.awt.Color(0, 0, 0));
        btn_oldagehome.setText("Old Age Home");
        btn_oldagehome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_oldagehome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_oldagehomeActionPerformed(evt);
            }
        });
        add(btn_oldagehome, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 251, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/guest_new.gif"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 140, 800, 630));
    }// </editor-fold>//GEN-END:initComponents

    private void btn_trustsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_trustsActionPerformed
        // TODO add your handling code here:
      CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        ViewTrustJPanel vnjp = new ViewTrustJPanel(userProcessContainer, system);
        userProcessContainer.add("vnjp", vnjp);
        cardLayout.next(userProcessContainer);
    }//GEN-LAST:event_btn_trustsActionPerformed

    private void btn_viewjobsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_viewjobsActionPerformed
        // TODO add your handling code here:
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        ApplyForJobJPanel afjp = new ApplyForJobJPanel(userProcessContainer, system, dB4OUtil, null, "G");
        userProcessContainer.add("afjp", afjp);
        cardLayout.next(userProcessContainer);
    }//GEN-LAST:event_btn_viewjobsActionPerformed

    private void btn_addfundraisersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addfundraisersActionPerformed
        // TODO add your handling code here:
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        FundingAgencySignUpJPanel fasujp = new FundingAgencySignUpJPanel(userProcessContainer, system, dB4OUtil);
        userProcessContainer.add("fasujp", fasujp);
        cardLayout.next(userProcessContainer);
    }//GEN-LAST:event_btn_addfundraisersActionPerformed

    private void btn_raiserequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_raiserequestActionPerformed
        // TODO add your handling code here:
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        IssueSignUpJPanel isjp = new IssueSignUpJPanel(userProcessContainer, system, dB4OUtil);
        userProcessContainer.add("IssueSignUpJPanel", isjp);
        cardLayout.next(userProcessContainer);
    }//GEN-LAST:event_btn_raiserequestActionPerformed

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
        // TODO add your handling code here:
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.remove(this);
        cardLayout.previous(userProcessContainer);
        dB4OUtil.storeSystem(system);
    }//GEN-LAST:event_btn_logoutActionPerformed

    private void btn_oldagehomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_oldagehomeActionPerformed
        // TODO add your handling code here:
   CardLayout  cardLayout = (CardLayout) userProcessContainer.getLayout();
        ViewOldAgeHomeJPanel oahj = new ViewOldAgeHomeJPanel(userProcessContainer, system);
        userProcessContainer.add("oahj",oahj);
        cardLayout.next(userProcessContainer);
    }//GEN-LAST:event_btn_oldagehomeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_addfundraisers;
    private javax.swing.JButton btn_logout;
    private javax.swing.JButton btn_oldagehome;
    private javax.swing.JButton btn_raiserequest;
    private javax.swing.JButton btn_trusts;
    private javax.swing.JButton btn_viewjobs;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblHeader;
    // End of variables declaration//GEN-END:variables
}
