/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.AdminWorkArea;

import Healthplus.Org.Org;
import Healthplus.Org.Org.OrgType;
import Healthplus.Org.OrgDirectory;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

public class ControlOrgPage extends javax.swing.JPanel {

    /**
     * Creates new form ControlOrgPage
     */
    private JPanel userProcessContainer;
    private OrgDirectory organizationDirectory;

    public ControlOrgPage(JPanel userProcessContainer, OrgDirectory organizationDirectory) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organizationDirectory = organizationDirectory;
        populateTable();
        populateCombo();
    }

    private void populateCombo() {
        combo_organizationtype.removeAllItems();
        for (OrgType type : Org.OrgType.values()) {
            if (!type.getValue().equals(OrgType.Admin.getValue()) && !type.getValue().equals(OrgType.SeniorCare.getValue()) && !type.getValue().equals(OrgType.Medical.getValue())) {
                combo_organizationtype.addItem(type);
            }
        }
    }

    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tblOrg.getModel();
        model.setRowCount(0);

        for (Org organization : organizationDirectory.getOrganizationList()) {
            Object[] row = new Object[1];
            row[0] = organization;

            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_backpage = new javax.swing.JButton();
        lblHeader = new javax.swing.JLabel();
        tblScrollPane = new javax.swing.JScrollPane();
        tblOrg = new javax.swing.JTable();
        btn_deleteOrg = new javax.swing.JButton();
        combo_organizationtype = new javax.swing.JComboBox();
        label_OrganizationType = new javax.swing.JLabel();
        btn_addOrg = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 238, 210));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_backpage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/backicon.jpeg"))); // NOI18N
        btn_backpage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backpageActionPerformed(evt);
            }
        });
        add(btn_backpage, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 110, 80));

        lblHeader.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        lblHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeader.setText("Manage Organization");
        add(lblHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, -1, -1));

        tblOrg.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Organization"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblOrg.setMinimumSize(new java.awt.Dimension(375, 0));
        tblScrollPane.setViewportView(tblOrg);

        add(tblScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, -1, 150));

        btn_deleteOrg.setBackground(new java.awt.Color(255, 255, 255));
        btn_deleteOrg.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        btn_deleteOrg.setText("Delete Organization");
        btn_deleteOrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteOrgActionPerformed(evt);
            }
        });
        add(btn_deleteOrg, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 310, -1, -1));

        combo_organizationtype.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        combo_organizationtype.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(combo_organizationtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 370, 150, -1));

        label_OrganizationType.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        label_OrganizationType.setText("Organization Type:");
        add(label_OrganizationType, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 370, -1, -1));

        btn_addOrg.setBackground(new java.awt.Color(255, 255, 255));
        btn_addOrg.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        btn_addOrg.setText("Add Organization");
        btn_addOrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addOrgActionPerformed(evt);
            }
        });
        add(btn_addOrg, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 430, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btn_addOrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addOrgActionPerformed
        // TODO add your handling code here:

        OrgType type = (OrgType) combo_organizationtype.getSelectedItem();
        System.out.println(type.name());
        for (Org organization : organizationDirectory.getOrganizationList()) {
            if(organization.getName().equals(type.name()+" Organization")){
                JOptionPane.showMessageDialog(null, "Organization already exists", "Warning", JOptionPane.WARNING_MESSAGE);
                return;
            }
        }     
        organizationDirectory.createOrganization(type);
        populateTable();
    }//GEN-LAST:event_btn_addOrgActionPerformed

    private void btn_deleteOrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteOrgActionPerformed
        // TODO add your handling code here:
        
        int selectedRow = tblOrg.getSelectedRow();
        if (selectedRow >= 0) {
            int dialogResult = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete the Organization?", "Warning", JOptionPane.YES_NO_OPTION);
            if (dialogResult == JOptionPane.YES_OPTION) {
                Org o = (Org) tblOrg.getValueAt(selectedRow, 0);
                organizationDirectory.deleteOrganization(o);
                populateTable();
                JOptionPane.showMessageDialog(null, "Organization deleted successfully", "Warning", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please select a row", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btn_deleteOrgActionPerformed

    private void btn_backpageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backpageActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btn_backpageActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_addOrg;
    private javax.swing.JButton btn_backpage;
    private javax.swing.JButton btn_deleteOrg;
    private javax.swing.JComboBox combo_organizationtype;
    private javax.swing.JLabel label_OrganizationType;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JTable tblOrg;
    private javax.swing.JScrollPane tblScrollPane;
    // End of variables declaration//GEN-END:variables
}
