/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.AdminWorkArea;

import Healthplus.Org.Org;
import Healthplus.Org.Org.OrgType;
import Healthplus.Org.OrgDirectory;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

public class ControlOldAgeHomeOrg_Page extends javax.swing.JPanel {

    /**
     * Creates new form ControlOldAgeHomeOrg_Page
     */
    private JPanel userProcessContainer;
    private OrgDirectory organizationDirectory;
    
    public ControlOldAgeHomeOrg_Page(JPanel userProcessContainer, OrgDirectory organizationDirectory) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organizationDirectory = organizationDirectory;
        populateTable();
        populateCombo();
    }
    
    private void populateCombo() {
        combo_organizationtype.removeAllItems();
        for (Org.OrgType type : Org.OrgType.values()) {
            if (type.getValue().equals(Org.OrgType.SeniorCare.getValue()) || type.getValue().equals(Org.OrgType.Medical.getValue())) {
                combo_organizationtype.addItem(type);
            }
        }
    }

    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tblOrg.getModel();
        model.setRowCount(0);

        for (Org organization : organizationDirectory.getOrganizationList()) {
                Object[] row = new Object[1];
                row[0] = organization;

                model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_backpage = new javax.swing.JButton();
        lblHeader = new javax.swing.JLabel();
        tblScrollPane = new javax.swing.JScrollPane();
        tblOrg = new javax.swing.JTable();
        btn_deleteorg = new javax.swing.JButton();
        label_organizationtype = new javax.swing.JLabel();
        combo_organizationtype = new javax.swing.JComboBox();
        btn_addOrg = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 249, 227));

        btn_backpage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/backicon.jpeg"))); // NOI18N
        btn_backpage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backpageActionPerformed(evt);
            }
        });

        lblHeader.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        lblHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeader.setText("Manage Organization");

        tblOrg.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Organization"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblOrg.setMinimumSize(new java.awt.Dimension(375, 0));
        tblScrollPane.setViewportView(tblOrg);

        btn_deleteorg.setBackground(new java.awt.Color(255, 255, 255));
        btn_deleteorg.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        btn_deleteorg.setText("Delete Organization");
        btn_deleteorg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_deleteorg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteorgActionPerformed(evt);
            }
        });

        label_organizationtype.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        label_organizationtype.setText("Organization Type:");

        combo_organizationtype.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        combo_organizationtype.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        combo_organizationtype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_organizationtypeActionPerformed(evt);
            }
        });

        btn_addOrg.setBackground(new java.awt.Color(255, 255, 255));
        btn_addOrg.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        btn_addOrg.setText("Add Organization");
        btn_addOrg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_addOrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addOrgActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(btn_backpage, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)
                        .addComponent(lblHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(tblScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(449, 449, 449)
                        .addComponent(btn_deleteorg))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(219, 219, 219)
                        .addComponent(label_organizationtype)
                        .addGap(71, 71, 71)
                        .addComponent(combo_organizationtype, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(309, 309, 309)
                        .addComponent(btn_addOrg)))
                .addContainerGap(179, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(lblHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_backpage, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(tblScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btn_deleteorg, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_organizationtype, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo_organizationtype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(btn_addOrg, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(334, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_backpageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backpageActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btn_backpageActionPerformed

    private void btn_deleteorgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteorgActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblOrg.getSelectedRow();
        if (selectedRow >= 0) {
            int dialogResult = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete the Organization?", "Warning", JOptionPane.YES_NO_OPTION);
            if (dialogResult == JOptionPane.YES_OPTION) {
                Org o = (Org) tblOrg.getValueAt(selectedRow, 0);
                organizationDirectory.deleteOrganization(o);
                populateTable();
                JOptionPane.showMessageDialog(null, "Organization deleted successfully", "Warning", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please select a row", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btn_deleteorgActionPerformed

    private void combo_organizationtypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_organizationtypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_organizationtypeActionPerformed

    private void btn_addOrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addOrgActionPerformed
        // TODO add your handling code here:
        OrgType type = (OrgType) combo_organizationtype.getSelectedItem();
        for (Org organization : organizationDirectory.getOrganizationList()) {
            if(organization.getName().equals(type.name()+" Organization")){
                JOptionPane.showMessageDialog(null, "Organization already exists", "Warning", JOptionPane.WARNING_MESSAGE);
                return;
            }
        }
        organizationDirectory.createOrganization(type);
        populateTable();
    }//GEN-LAST:event_btn_addOrgActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_addOrg;
    private javax.swing.JButton btn_backpage;
    private javax.swing.JButton btn_deleteorg;
    private javax.swing.JComboBox combo_organizationtype;
    private javax.swing.JLabel label_organizationtype;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JTable tblOrg;
    private javax.swing.JScrollPane tblScrollPane;
    // End of variables declaration//GEN-END:variables
}
