/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.AdminWorkArea;

import Healthplus.E_System;
import Healthplus.Enterprises.Enterprise;
import Healthplus.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

public class OldAgeHomeAdminWorkArea_Page extends javax.swing.JPanel {

    /**
     * Creates new form OldAgeHomeAdminWorkArea_Page
     */
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private E_System system;
    
    public OldAgeHomeAdminWorkArea_Page(JPanel userProcessContainer, UserAccount userAccount, Enterprise enterprise,
            E_System system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.enterprise = enterprise;
        this.system = system;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHeader = new javax.swing.JLabel();
        btn_ManageOrg = new javax.swing.JButton();
        btn_publishJobs = new javax.swing.JButton();
        btn_manageJobAppl = new javax.swing.JButton();
        btn_manageUserAcc = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 255, 255));

        lblHeader.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        lblHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeader.setText("Admin Page");

        btn_ManageOrg.setBackground(new java.awt.Color(255, 255, 255));
        btn_ManageOrg.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        btn_ManageOrg.setText("Manage Organization");
        btn_ManageOrg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_ManageOrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ManageOrgActionPerformed(evt);
            }
        });

        btn_publishJobs.setBackground(new java.awt.Color(255, 255, 255));
        btn_publishJobs.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        btn_publishJobs.setText("Publish Jobs");
        btn_publishJobs.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_publishJobs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_publishJobsActionPerformed(evt);
            }
        });

        btn_manageJobAppl.setBackground(new java.awt.Color(255, 255, 255));
        btn_manageJobAppl.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        btn_manageJobAppl.setText("Manage Job Applications");
        btn_manageJobAppl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_manageJobAppl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_manageJobApplActionPerformed(evt);
            }
        });

        btn_manageUserAcc.setBackground(new java.awt.Color(255, 255, 255));
        btn_manageUserAcc.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        btn_manageUserAcc.setText("Manage Employee User Account");
        btn_manageUserAcc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_manageUserAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_manageUserAccActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/adminworkarea.gif"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(528, 528, 528)
                        .addComponent(lblHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(btn_ManageOrg)
                                .addGap(37, 37, 37))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_manageJobAppl)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_publishJobs, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_manageUserAcc, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_ManageOrg, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_publishJobs, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(110, 110, 110)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_manageJobAppl, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_manageUserAcc, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(221, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ManageOrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ManageOrgActionPerformed
        // TODO add your handling code here:
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        ControlOldAgeHomeOrg_Page mojp = new ControlOldAgeHomeOrg_Page(userProcessContainer, enterprise.getOrganizationDirectory());
        userProcessContainer.add("mojp", mojp);
        cardLayout.next(userProcessContainer);
    }//GEN-LAST:event_btn_ManageOrgActionPerformed

    private void btn_publishJobsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_publishJobsActionPerformed
        // TODO add your handling code here:
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        PublishOldAgeHomeJobs_Page pjjp = new PublishOldAgeHomeJobs_Page(userProcessContainer, system.getJobDirectory(), userAccount, system);
        userProcessContainer.add("pjjp", pjjp);
        cardLayout.next(userProcessContainer);
    }//GEN-LAST:event_btn_publishJobsActionPerformed

    private void btn_manageJobApplActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_manageJobApplActionPerformed
        // TODO add your handling code here:
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        ControlOldAgeHomeJobApplications_Page mjajp = new ControlOldAgeHomeJobApplications_Page(userProcessContainer, enterprise, system, userAccount);
        userProcessContainer.add("mjajp", mjajp);
        cardLayout.next(userProcessContainer);
    }//GEN-LAST:event_btn_manageJobApplActionPerformed

    private void btn_manageUserAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_manageUserAccActionPerformed
        // TODO add your handling code here:
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        ControlOldAgeHomeWorkerUserAcc_Page meuajp = new ControlOldAgeHomeWorkerUserAcc_Page(userProcessContainer, enterprise, system);
        userProcessContainer.add("meuajp", meuajp);
        cardLayout.next(userProcessContainer);
    }//GEN-LAST:event_btn_manageUserAccActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ManageOrg;
    private javax.swing.JButton btn_manageJobAppl;
    private javax.swing.JButton btn_manageUserAcc;
    private javax.swing.JButton btn_publishJobs;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblHeader;
    // End of variables declaration//GEN-END:variables
}
