/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.AdminWorkArea;

import Healthplus.E_System;
import Healthplus.Enterprises.Enterprise;
import Healthplus.Job.Job;
import Healthplus.Job.JobDirectory;
import Healthplus.Network.City;
import Healthplus.Network.Country;
import Healthplus.Network.State;
import Healthplus.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;


public class PublishOldAgeHomeJobs_Page extends javax.swing.JPanel {

    /**
     * Creates new form PublishOldAgeHomeJobs_Page
     */
    private JPanel userProcessContainer;
    private JobDirectory jobDirectory;
    private UserAccount userAccount;
    private E_System system;
    
    public PublishOldAgeHomeJobs_Page(JPanel userProcessContainer, JobDirectory jobDirectory, UserAccount userAccount, E_System system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.jobDirectory = jobDirectory;
        this.userAccount = userAccount;
        this.system = system;
        populateTable();
    }
    
    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tblJobs.getModel();
        model.setRowCount(0);

        if (jobDirectory != null) {
            for (Job job : jobDirectory.getJobList()) {
                Object[] row = new Object[5];
          
                for (Country c : system.getNetworkList()) {
                    for (State s : c.getStateList()) {
                        for (City city : s.getCityList()) {
                            for (Enterprise e : city.getEnterpriseDirectory().getEnterpriseList()) {
                                for (UserAccount ua : e.getUserAccountDirectory().getUserAccountList()) {
                                    if (userAccount.getUsername().equals(ua.getUsername())) {
                                        if (e.equals(job.getEnterprise())) {
                                            row[0] = c;
                                            row[1] = s;
                                            row[2] = city;
                                            row[3] = job.getEnterprise();
                                            row[4] = job;
                                            model.addRow(row);
                                        }
                                    }
                                }
                            }
                        }
                    }
                }    
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_backpage = new javax.swing.JButton();
        lblHeader = new javax.swing.JLabel();
        tblScrollPane = new javax.swing.JScrollPane();
        tblJobs = new javax.swing.JTable();
        btn_removejob = new javax.swing.JButton();
        label_jobTitle = new javax.swing.JLabel();
        text_jobtitle = new javax.swing.JTextField();
        btn_postJob = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 243, 218));

        btn_backpage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/backicon.jpeg"))); // NOI18N
        btn_backpage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backpageActionPerformed(evt);
            }
        });

        lblHeader.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        lblHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeader.setText("Publish Jobs");

        tblJobs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Country", "State", "City", "Old Age Home", "Job Title"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblJobs.setMinimumSize(new java.awt.Dimension(375, 0));
        tblScrollPane.setViewportView(tblJobs);

        btn_removejob.setBackground(new java.awt.Color(255, 255, 255));
        btn_removejob.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        btn_removejob.setText("Delete Job");
        btn_removejob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_removejobActionPerformed(evt);
            }
        });

        label_jobTitle.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        label_jobTitle.setText("Job Title:");

        text_jobtitle.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N

        btn_postJob.setBackground(new java.awt.Color(255, 255, 255));
        btn_postJob.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        btn_postJob.setText("Submit");
        btn_postJob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_postJobActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tblScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(57, 57, 57)
                            .addComponent(btn_backpage, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(lblHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(506, 506, 506)
                            .addComponent(btn_removejob, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(269, 269, 269)
                            .addComponent(label_jobTitle)
                            .addGap(37, 37, 37)
                            .addComponent(text_jobtitle, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(329, 329, 329)
                            .addComponent(btn_postJob, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(174, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lblHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_backpage, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37)
                .addComponent(tblScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_removejob)
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_jobTitle)
                    .addComponent(text_jobtitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(btn_postJob)
                .addContainerGap(305, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_backpageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backpageActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btn_backpageActionPerformed

    private void btn_removejobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_removejobActionPerformed
        // TODO add your handling code here:

        int selectedRow = tblJobs.getSelectedRow();
        if (selectedRow >= 0) {
            int dialogResult = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete the Job?", "Warning", JOptionPane.YES_NO_OPTION);
            if (dialogResult == JOptionPane.YES_OPTION) {
                Job job = (Job) tblJobs.getValueAt(selectedRow, 4);

                system.getJobDirectory().removeJob(job);
                populateTable();
                JOptionPane.showMessageDialog(null, "Job deleted successfully", "Warning", JOptionPane.WARNING_MESSAGE);

            }

        } else {
            JOptionPane.showMessageDialog(null, "Please select a row", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btn_removejobActionPerformed

    private void btn_postJobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_postJobActionPerformed
        // TODO add your handling code here:
        String name = text_jobtitle.getText();
        if (!name.equals("")) {

            // validate name
            String regex = "^[a-z A-Z]+$";
            Pattern namePattern = Pattern.compile(regex);
            Matcher nameMatcher = namePattern.matcher(name);

            if (!nameMatcher.matches()) {
                JOptionPane.showMessageDialog(null, "Invalid characters in job title", "Warning", JOptionPane.WARNING_MESSAGE);
                return;
            }

            if(name.equalsIgnoreCase("CareTaker") || name.equalsIgnoreCase("Doctor")){
                for (Country c : system.getNetworkList()) {
                    for (State s : c.getStateList()) {
                        for (City cy : s.getCityList()) {
                            for (Enterprise e : cy.getEnterpriseDirectory().getEnterpriseList()) {
                                for (UserAccount ua : e.getUserAccountDirectory().getUserAccountList()) {
                                    if (ua.getUsername().equals(userAccount.getUsername())) {
                                        Job job = jobDirectory.createJob(name);
                                        job.setEnterprise(e);
                                    }
                                }
                            }
                        }
                    }
                }
            }else{
                JOptionPane.showMessageDialog(null, "Job can be posted for 'CareTaker' or 'Doctor' position only", "Info", JOptionPane.INFORMATION_MESSAGE);
                return;
            }

            populateTable();
            text_jobtitle.setText("");
            JOptionPane.showMessageDialog(null, "Job posted successfully", "Info", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "Please enter text", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btn_postJobActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_backpage;
    private javax.swing.JButton btn_postJob;
    private javax.swing.JButton btn_removejob;
    private javax.swing.JLabel label_jobTitle;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JTable tblJobs;
    private javax.swing.JScrollPane tblScrollPane;
    private javax.swing.JTextField text_jobtitle;
    // End of variables declaration//GEN-END:variables
}
