/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.ManagerWorkArea;

import Healthplus.E_System;
import Healthplus.Enterprises.Enterprise;
import Healthplus.Org.Org;
import Healthplus.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;


public class ManagerWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManagerWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private Org organization;
    private Enterprise enterprise;
    private E_System system;
    public ManagerWorkAreaJPanel(JPanel userProcessContainer,E_System system, UserAccount userAccount, Org organization, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer; 
        this.userAccount = userAccount;
        this.organization = organization;
        this.enterprise = enterprise;
        this.system = system;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_managerfundraisers = new javax.swing.JButton();
        btn_posttask = new javax.swing.JButton();
        btn_issues = new javax.swing.JButton();
        btn_viewprojects = new javax.swing.JButton();
        btn_acc = new javax.swing.JButton();
        btn_coord = new javax.swing.JButton();
        lblHeader = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        
        });
        add(btn_managerfundraisers, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 220, -1));

        btn_posttask.setBackground(new java.awt.Color(255, 255, 255));
        btn_posttask.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        btn_posttask.setText("Post Tasks");
        btn_posttask.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_posttask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_posttaskActionPerformed(evt);
            }
        });
        add(btn_posttask, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 217, -1));

        btn_issues.setBackground(new java.awt.Color(255, 255, 255));
        btn_issues.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        btn_issues.setText("View Issues");
        btn_issues.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_issues.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_issuesActionPerformed(evt);
            }
        });
        add(btn_issues, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 217, -1));

        btn_viewprojects.setBackground(new java.awt.Color(255, 255, 255));
        btn_viewprojects.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        btn_viewprojects.setText("Projects");
        btn_viewprojects.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_viewprojects.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_viewprojectsActionPerformed(evt);
            }
        });
        add(btn_viewprojects, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, 217, -1));

       
    private javax.swing.JButton btn_acc;
    private javax.swing.JButton btn_coord;

    // End of variables declaration//GEN-END:variables
}
