/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.AttendantWorkArea;

import Healthplus.E_System;
import Healthplus.Enterprises.Enterprise;
import Healthplus.Org.Org;
import Healthplus.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

public class AttendantWorkArea_Page extends javax.swing.JPanel {

    /**
     * Creates new form AttendantWorkArea_Page
     */
    private JPanel userProcessContainer;
    private E_System system;
    private UserAccount userAccount;
    private Org organization;
    private Enterprise enterprise;

    public AttendantWorkArea_Page(JPanel userProcessContainer, E_System system, UserAccount userAccount, Org organization, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        this.userAccount = userAccount;
        this.organization = organization;
        this.enterprise = enterprise;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHeader = new javax.swing.JLabel();
        btn_manageSeniorCare = new javax.swing.JButton();
        btn_viewSenior = new javax.swing.JButton();
        btn_gotreat = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 208, 194));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblHeader.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        lblHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeader.setText("CareTaker Work Area");
        add(lblHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 40, 270, 26));

        btn_manageSeniorCare.setBackground(new java.awt.Color(255, 255, 255));
        btn_manageSeniorCare.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        btn_manageSeniorCare.setText("Manage Senior Care");
        btn_manageSeniorCare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_manageSeniorCareActionPerformed(evt);
            }
        });
        add(btn_manageSeniorCare, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 350, 200, 40));

        btn_viewSenior.setBackground(new java.awt.Color(255, 255, 255));
        btn_viewSenior.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        btn_viewSenior.setText("View Seniors");
        btn_viewSenior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_viewSeniorActionPerformed(evt);
            }
        });
        add(btn_viewSenior, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 430, 200, 40));

        btn_gotreat.setBackground(new java.awt.Color(255, 255, 255));
        btn_gotreat.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        btn_gotreat.setText("Send Senior for Treatment");
        btn_gotreat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_gotreatActionPerformed(evt);
            }
        });
        add(btn_gotreat, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 510, 200, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/caretaker.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 550, 410));
    }// </editor-fold>//GEN-END:initComponents

    private void btn_manageSeniorCareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_manageSeniorCareActionPerformed
        // TODO add your handling code here:
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        ManageSeniorCare_Page opjp = new ManageSeniorCare_Page(userProcessContainer, system, userAccount, organization, enterprise);
        userProcessContainer.add("OngoingProjectsJPanel", opjp);
        cardLayout.next(userProcessContainer);
    }//GEN-LAST:event_btn_manageSeniorCareActionPerformed

    private void btn_viewSeniorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_viewSeniorActionPerformed
        // TODO add your handling code here:

        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        ViewSeniorCare_Page abcd = new ViewSeniorCare_Page(userProcessContainer, system, userAccount, organization, enterprise);
        userProcessContainer.add("abcd", abcd);
        cardLayout.next(userProcessContainer);
    }//GEN-LAST:event_btn_viewSeniorActionPerformed

    private void btn_gotreatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_gotreatActionPerformed
        // TODO add your handling code here:
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
            SendSeniorForTreatment_Page efgh = new SendSeniorForTreatment_Page(userProcessContainer, system, userAccount, organization, enterprise);
        userProcessContainer.add("efgh", efgh);
        cardLayout.next(userProcessContainer);
    }//GEN-LAST:event_btn_gotreatActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_gotreat;
    private javax.swing.JButton btn_manageSeniorCare;
    private javax.swing.JButton btn_viewSenior;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblHeader;
    // End of variables declaration//GEN-END:variables
}
