/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.ApplicantWorkArea;

import Healthplus.DB4OUtil.DB4OUtil;
import Healthplus.E_System;
import Healthplus.Enterprises.Enterprise;
import Healthplus.Org.Org;
import Healthplus.UserAccount.UserAccount;
import UI.Login_Panel;
import java.awt.CardLayout;
import javax.swing.JPanel;


public class ApplicantHome_Page extends javax.swing.JPanel {

    /**
     * Creates new form ApplicantHome_Page
     */
    private JPanel mainContainer;
    private E_System system;
    private DB4OUtil dB4OUtil;
    private UserAccount userAccount;

    public ApplicantHome_Page(JPanel mainContainer, E_System system, DB4OUtil dB4OUtil, UserAccount userAccount) {
        initComponents();
        this.mainContainer = mainContainer;
        this.system = system;
        this.dB4OUtil = dB4OUtil;
        this.userAccount = userAccount;
        
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        ApplicantWorkArea_Page awajp = new ApplicantWorkArea_Page(userProcessContainer, system, userAccount, dB4OUtil);
        userProcessContainer.add("ApplicantWorkAreaJPanel", awajp);
        cardLayout.next(userProcessContainer);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPane = new javax.swing.JSplitPane();
        controlJPanel = new javax.swing.JPanel();
        btn_viewpanel = new javax.swing.JButton();
        btn_workpanel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btn_logoutuser = new javax.swing.JButton();
        userProcessContainer = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(900, 900));
        setPreferredSize(new java.awt.Dimension(900, 900));
        setLayout(new java.awt.CardLayout());

        splitPane.setBackground(new java.awt.Color(255, 255, 255));
        splitPane.setMaximumSize(new java.awt.Dimension(900, 900));
        splitPane.setMinimumSize(new java.awt.Dimension(900, 900));

        controlJPanel.setBackground(new java.awt.Color(255, 183, 183));
        controlJPanel.setMaximumSize(new java.awt.Dimension(200, 200));
        controlJPanel.setMinimumSize(new java.awt.Dimension(200, 200));

        btn_viewpanel.setBackground(new java.awt.Color(255, 255, 255));
        btn_viewpanel.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        btn_viewpanel.setText("View Area");
        btn_viewpanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_viewpanelActionPerformed(evt);
            }
        });

        btn_workpanel.setBackground(new java.awt.Color(255, 255, 255));
        btn_workpanel.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        btn_workpanel.setText("Work Area");
        btn_workpanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_workpanelActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/gif1.png"))); // NOI18N

        btn_logoutuser.setBackground(new java.awt.Color(255, 255, 255));
        btn_logoutuser.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        btn_logoutuser.setText("Logout");
        btn_logoutuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutuserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout controlJPanelLayout = new javax.swing.GroupLayout(controlJPanel);
        controlJPanel.setLayout(controlJPanelLayout);
        controlJPanelLayout.setHorizontalGroup(
            controlJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(controlJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(controlJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, controlJPanelLayout.createSequentialGroup()
                            .addGroup(controlJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btn_viewpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btn_workpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(336, 336, 336))
                        .addGroup(controlJPanelLayout.createSequentialGroup()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(309, 309, 309)))
                    .addComponent(btn_logoutuser)))
        );
        controlJPanelLayout.setVerticalGroup(
            controlJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlJPanelLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addComponent(btn_workpanel)
                .addGap(32, 32, 32)
                .addComponent(btn_viewpanel)
                .addGap(121, 121, 121)
                .addComponent(btn_logoutuser, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(335, Short.MAX_VALUE))
        );

        splitPane.setLeftComponent(controlJPanel);

        userProcessContainer.setBackground(new java.awt.Color(255, 255, 255));
        userProcessContainer.setMaximumSize(new java.awt.Dimension(700, 700));
        userProcessContainer.setMinimumSize(new java.awt.Dimension(700, 700));
        userProcessContainer.setLayout(new java.awt.CardLayout());
        splitPane.setRightComponent(userProcessContainer);

        add(splitPane, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void btn_logoutuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutuserActionPerformed
        // TODO add your handling code here:

        CardLayout cardLayout = (CardLayout) mainContainer.getLayout();
        Login_Panel ljp = new Login_Panel(mainContainer, system, dB4OUtil);
        mainContainer.add("ljp", ljp);
        cardLayout.next(mainContainer);
        dB4OUtil.storeSystem(system);
    }//GEN-LAST:event_btn_logoutuserActionPerformed

    private void btn_viewpanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_viewpanelActionPerformed
        // TODO add your handling code here:
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        ApplicantViewArea_Page avajp = new ApplicantViewArea_Page(userProcessContainer, system, dB4OUtil);
        userProcessContainer.add("avajp", avajp);
        cardLayout.next(userProcessContainer);
    }//GEN-LAST:event_btn_viewpanelActionPerformed

    private void btn_workpanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_workpanelActionPerformed
        // TODO add your handling code here:

        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        ApplicantWorkArea_Page awajp = new ApplicantWorkArea_Page(userProcessContainer, system, userAccount, dB4OUtil);
        userProcessContainer.add("ApplicantWorkAreaJPanel", awajp);
        cardLayout.next(userProcessContainer);
    }//GEN-LAST:event_btn_workpanelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_logoutuser;
    private javax.swing.JButton btn_viewpanel;
    private javax.swing.JButton btn_workpanel;
    private javax.swing.JPanel controlJPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSplitPane splitPane;
    private javax.swing.JPanel userProcessContainer;
    // End of variables declaration//GEN-END:variables
}
