/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.GuestWorkArea;

import Healthplus.DB4OUtil.DB4OUtil;
import Healthplus.E_System;
import Healthplus.Enterprises.Enterprise;
import Healthplus.Job.Job;
import Healthplus.Network.City;
import Healthplus.Network.Country;
import Healthplus.Network.State;
import Healthplus.Org.AdminOrg;
import Healthplus.Org.Org;
import Healthplus.UserAccount.UserAccount;
import Healthplus.WorkQueue.JobWorkRequest;
import Healthplus.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.util.ConcurrentModificationException;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;



public class ApplyForJobJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private E_System system;
    private UserAccount userAccount;
    private DB4OUtil dB4OUtil;
    private String user;

    /**
     * Creates new form ApplyForJobJPanel
     */
    
    public ApplyForJobJPanel(JPanel userProcessContainer, E_System system, DB4OUtil dB4OUtil, UserAccount userAccount, String user) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        this.dB4OUtil = dB4OUtil;
        this.userAccount = userAccount;
        this.user = user;
        //this.enterprise = enterprise;
        populateTable();
    }

    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tblJobs.getModel();

        model.setRowCount(0);

        if (system.getJobDirectory().getJobList() != null) {
            for (Job job : system.getJobDirectory().getJobList()) {
                Object[] row = new Object[5];
                row[3] = job.getEnterprise();
                row[4] = job;

                for (Country c : system.getNetworkList()) {
                    for (State s : c.getStateList()) {
                        for (City city : s.getCityList()) {
                            for (Enterprise e : city.getEnterpriseDirectory().getEnterpriseList()) {
                                if (e.equals(job.getEnterprise())) {
                                    row[0] = c;
                                    row[1] = s;
                                    row[2] = city;
                                }
                            }
                        }
                    }
                }
                model.addRow(row);
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHeader = new javax.swing.JLabel();
        tblScrollPane = new javax.swing.JScrollPane();
        tblJobs = new javax.swing.JTable();
        btn_applyforJob = new javax.swing.JButton();
        btn_back = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 222, 205));
        setMaximumSize(new java.awt.Dimension(700, 700));
        setMinimumSize(new java.awt.Dimension(700, 700));
        setPreferredSize(new java.awt.Dimension(700, 700));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblHeader.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        lblHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeader.setText("Apply For Job");
        add(lblHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 450, 26));

        tblJobs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Country", "State", "City", "Trust", "Job Title"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblJobs.setMinimumSize(new java.awt.Dimension(375, 0));
        tblJobs.getTableHeader().setReorderingAllowed(false);
        tblScrollPane.setViewportView(tblJobs);
        if (tblJobs.getColumnModel().getColumnCount() > 0) {
            tblJobs.getColumnModel().getColumn(0).setResizable(false);
            tblJobs.getColumnModel().getColumn(1).setResizable(false);
            tblJobs.getColumnModel().getColumn(2).setResizable(false);
            tblJobs.getColumnModel().getColumn(3).setResizable(false);
            tblJobs.getColumnModel().getColumn(4).setResizable(false);
        }

        add(tblScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, -1, 140));

        btn_applyforJob.setBackground(new java.awt.Color(255, 255, 255));
        btn_applyforJob.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        btn_applyforJob.setText("Apply");
        btn_applyforJob.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_applyforJob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_applyforJobActionPerformed(evt);
            }
        });
        add(btn_applyforJob, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 138, 90, 40));

        btn_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/backicon.jpeg"))); // NOI18N
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });
        add(btn_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, 110, 70));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/job.gif"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 950, 630));
    }// </editor-fold>//GEN-END:initComponents

    private void btn_applyforJobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_applyforJobActionPerformed
        // TODO add your handling code here:

        int selectedRow = tblJobs.getSelectedRow();

        if (selectedRow >= 0) {
            Job job = (Job) tblJobs.getValueAt(selectedRow, 4);
            Enterprise enterprise = (Enterprise) tblJobs.getValueAt(selectedRow, 3);

            if (user.equals("G")) {
                SignUpJPanel sujp = new SignUpJPanel(userProcessContainer, system, dB4OUtil, enterprise, job);
                userProcessContainer.add("SignUpJPanel", sujp);
                CardLayout layout = (CardLayout) userProcessContainer.getLayout();
                layout.next(userProcessContainer);
                
            } else {
                try{
                for (WorkRequest wr : userAccount.getWorkQueue().getWorkRequestList()) {
                    if (wr instanceof JobWorkRequest) {
                        if (((JobWorkRequest) wr).getJob().equals(job)) {
                            if (wr.getSender().equals(userAccount)) {
                                JOptionPane.showMessageDialog(this, "You have already applied for this job", "Information", JOptionPane.WARNING_MESSAGE);
                            }
                        } else {
                            int dialogResult = JOptionPane.showConfirmDialog(this, "Are you sure you want to apply for the job?", "Information", JOptionPane.YES_NO_OPTION);
                            if (dialogResult == JOptionPane.YES_OPTION) {
                                sendWorkRequest(userAccount, job, enterprise);
                            }

                        }
                    }

                }

            }catch(ConcurrentModificationException ex){
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
            }

        } else {
            JOptionPane.showMessageDialog(null, "Please select a row to continue", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_applyforJobActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btn_backActionPerformed

    public void sendWorkRequest(UserAccount userAccount, Job job, Enterprise enterprise) {

        JobWorkRequest request = new JobWorkRequest();

        request.setSender(userAccount);
        request.setJob(job);
        request.setStatus("Sent");

        Org org = null;
        for (Org organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
            if (organization instanceof AdminOrg) {
                org = organization;
//                for(UserAccount ua: enterprise.getUserAccountDirectory().getUserAccountList()){
//                    if(ua.getRole().getName().equals("Admin Type")){
//                         request.setReceiver(ua);
//                         ua.getWorkQueue().getWorkRequestList().add(request);
//                }
//                }

                break;
            }
        }
        if (org != null) {
            org.getWorkQueue().getWorkRequestList().add(request);
            userAccount.getWorkQueue().getWorkRequestList().add(request);
        }

        JOptionPane.showMessageDialog(null, "Job applied Successfully", "Information", JOptionPane.INFORMATION_MESSAGE);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_applyforJob;
    private javax.swing.JButton btn_back;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JTable tblJobs;
    private javax.swing.JScrollPane tblScrollPane;
    // End of variables declaration//GEN-END:variables
}
