/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.GuestWorkArea;

import Healthplus.Applicant.Applicant;
import Healthplus.Applicant.ApplicantDirectory;
import Healthplus.DB4OUtil.DB4OUtil;
import Healthplus.E_System;
import Healthplus.Enterprises.Enterprise;
import Healthplus.Role.ApplicantRole;
import Healthplus.UserAccount.UserAccount;
import UI.ApplicantWorkArea.ApplicantHome_Page;
import java.awt.CardLayout;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;


public class IssueSignUpJPanel extends javax.swing.JPanel {

    /**
     * Creates new form IssueSignUpJPanel
     */
    private JPanel userProcessContainer;
    private E_System system;
    private DB4OUtil dB4OUtil;

    public IssueSignUpJPanel(JPanel userProcessContainer, E_System system, DB4OUtil dB4OUtil) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        this.dB4OUtil = dB4OUtil;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_title = new javax.swing.JLabel();
        btn_createnewacc = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        text_username = new javax.swing.JTextField();
        label_username = new javax.swing.JLabel();
        label_confirmpswd = new javax.swing.JLabel();
        text_personname = new javax.swing.JTextField();
        text_confirmpswd = new javax.swing.JPasswordField();
        text_userpassword = new javax.swing.JPasswordField();
        label_personname = new javax.swing.JLabel();
        label_userpassword = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_title.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        label_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_title.setText("Create new account");
        add(label_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, 310, 50));

        btn_createnewacc.setBackground(new java.awt.Color(113, 160, 160));
        btn_createnewacc.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        btn_createnewacc.setText("Add Account");
        btn_createnewacc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_createnewaccActionPerformed(evt);
            }
        });
        add(btn_createnewacc, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, -1, -1));

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/backicon.jpeg"))); // NOI18N
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 520, 100, 80));

        text_username.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        add(text_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 150, -1));

        label_username.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        label_username.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        label_username.setText("User Name");
        add(label_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 90, -1));

        label_confirmpswd.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        label_confirmpswd.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        label_confirmpswd.setText("Confirm Password");
        add(label_confirmpswd, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 140, -1));

        text_personname.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        add(text_personname, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 150, -1));

        text_confirmpswd.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        add(text_confirmpswd, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 150, -1));

        text_userpassword.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        add(text_userpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 150, -1));

        label_personname.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        label_personname.setText("Name");
        add(label_personname, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, -1, -1));

        label_userpassword.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        label_userpassword.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        label_userpassword.setText("Password");
        add(label_userpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 90, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/sign.gif"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 110, 510, 440));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/plus.gif"))); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -20, 180, 190));
    }// </editor-fold>//GEN-END:initComponents

    private void btn_createnewaccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_createnewaccActionPerformed
        // TODO add your handling code here:

        try {
            String name = text_personname.getText();
            String userName = text_username.getText();

            //Getting the password
            char[] passwordCharArray = text_userpassword.getPassword();
            String password = String.valueOf(passwordCharArray);

            char[] confirmPasswordCharArray = text_confirmpswd.getPassword();
            String confirmPassword = String.valueOf(confirmPasswordCharArray);

            if (userName.equals("")) {
                JOptionPane.showMessageDialog(null, "Please enter values for user name", "Warning", JOptionPane.WARNING_MESSAGE);
                return;
            } else if (password.equals("")) {
                JOptionPane.showMessageDialog(null, "Please enter values for password", "Warning", JOptionPane.WARNING_MESSAGE);
                return;
            } else if (confirmPassword.equals("")) {
                JOptionPane.showMessageDialog(null, "Please enter values for confirm password", "Warning", JOptionPane.WARNING_MESSAGE);
                return;
            }
            // validate username
            String regex = "^[a-z A-Z]+$";
            Pattern namePattern = Pattern.compile(regex);
            Matcher nameMatcher = namePattern.matcher(userName);

            if (!nameMatcher.matches()) {
                JOptionPane.showMessageDialog(null, "Invalid characters in user name", "Warning", JOptionPane.WARNING_MESSAGE);
                return;
            }

            // check if password and confirmPassword are same
            if (!(password.equals(confirmPassword))) {
                JOptionPane.showMessageDialog(null, "Please enter same password in both password fields", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // check if password length is between 4-10 or give error
            if (password.length() > 10) {
                JOptionPane.showMessageDialog(null, "Password should not have more than 10 characters", "Warning", JOptionPane.WARNING_MESSAGE);
                return;
            } else if (password.length() < 4) {
                JOptionPane.showMessageDialog(null, "Password should have 4 to 10 characters", "Warning", JOptionPane.WARNING_MESSAGE);
                return;
            }

            if (system.getUserAccountDirectory().checkIfUsernameIsUnique(userName)) {
                UserAccount userAccount = system.getUserAccountDirectory().createUserAccount(userName, password, null, new ApplicantRole());
                Applicant applicant = system.getApplicantDirectory().createApplicant(name);
                userAccount.setApplicant(applicant);

                JOptionPane.showMessageDialog(null, "User account added successfully", "Information", JOptionPane.INFORMATION_MESSAGE);

//                CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
//                RaiseIssueJPanel rijp = new RaiseIssueJPanel(userProcessContainer, userAccount, system);
//                userProcessContainer.add("rijp", rijp);
//                cardLayout.next(userProcessContainer);
                CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
                ApplicantHome_Page ahjp = new ApplicantHome_Page(userProcessContainer, system, dB4OUtil, userAccount);
                userProcessContainer.add("ahjp", ahjp);
                cardLayout.next(userProcessContainer);
            } else {
                JOptionPane.showMessageDialog(null, "Username already exists. Kindly use another username", "Error", JOptionPane.ERROR_MESSAGE);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"All set");
        }
    }//GEN-LAST:event_btn_createnewaccActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btn_createnewacc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel label_confirmpswd;
    private javax.swing.JLabel label_personname;
    private javax.swing.JLabel label_title;
    private javax.swing.JLabel label_username;
    private javax.swing.JLabel label_userpassword;
    private javax.swing.JPasswordField text_confirmpswd;
    private javax.swing.JTextField text_personname;
    private javax.swing.JTextField text_username;
    private javax.swing.JPasswordField text_userpassword;
    // End of variables declaration//GEN-END:variables
}
