/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.GuestWorkArea;

import Healthplus.E_System;
import Healthplus.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

public class RaiseIssueJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private E_System system;
    private UserAccount userAccount;

    /**
     * Creates new form RaiseIssueJPanel
     */
    public RaiseIssueJPanel(JPanel userProcessContainer, UserAccount userAccount, E_System system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        this.userAccount = userAccount;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHeader = new javax.swing.JLabel();
        btn_provideMedications = new javax.swing.JButton();
        btn_treatment = new javax.swing.JButton();
        btn_basicamenities = new javax.swing.JButton();
        btn_backpage = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 219, 198));
        setMaximumSize(new java.awt.Dimension(700, 700));
        setMinimumSize(new java.awt.Dimension(700, 700));
        setPreferredSize(new java.awt.Dimension(700, 700));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblHeader.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        lblHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeader.setText("Raise A Request");
        add(lblHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 100, 180, 26));

        btn_provideMedications.setBackground(new java.awt.Color(255, 255, 255));
        btn_provideMedications.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        btn_provideMedications.setForeground(new java.awt.Color(0, 0, 0));
        btn_provideMedications.setText("Provide Medications");
        btn_provideMedications.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_provideMedicationsActionPerformed(evt);
            }
        });
        add(btn_provideMedications, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 182, 30));

        btn_treatment.setBackground(new java.awt.Color(255, 255, 255));
        btn_treatment.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        btn_treatment.setForeground(new java.awt.Color(0, 0, 0));
        btn_treatment.setText("Provide Treatment");
        btn_treatment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_treatmentActionPerformed(evt);
            }
        });
        add(btn_treatment, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, 182, 30));

        btn_basicamenities.setBackground(new java.awt.Color(255, 255, 255));
        btn_basicamenities.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        btn_basicamenities.setForeground(new java.awt.Color(0, 0, 0));
        btn_basicamenities.setText("Donation of Basic Amenities");
        btn_basicamenities.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_basicamenitiesActionPerformed(evt);
            }
        });
        add(btn_basicamenities, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 210, 30));

        btn_backpage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/backicon.jpeg"))); // NOI18N
        btn_backpage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backpageActionPerformed(evt);
            }
        });
        add(btn_backpage, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, 110, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/request.jpg"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 330, 560, 310));
    }// </editor-fold>//GEN-END:initComponents

    private void btn_provideMedicationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_provideMedicationsActionPerformed

        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        RaiseIssueWorkRequestJPanel rirwjp = new RaiseIssueWorkRequestJPanel(userProcessContainer, userAccount, "Medications", system);
        userProcessContainer.add("rirwjp", rirwjp);
        cardLayout.next(userProcessContainer);
    }//GEN-LAST:event_btn_provideMedicationsActionPerformed

    private void btn_treatmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_treatmentActionPerformed
        // TODO add your handling code here:
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        RaiseIssueWorkRequestJPanel rirwjp = new RaiseIssueWorkRequestJPanel(userProcessContainer, userAccount, "Treatment Senior", system);
        userProcessContainer.add("rirwjp", rirwjp);
        cardLayout.next(userProcessContainer);
    }//GEN-LAST:event_btn_treatmentActionPerformed

    private void btn_basicamenitiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_basicamenitiesActionPerformed
        // TODO add your handling code here:
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        RaiseIssueWorkRequestJPanel rirwjp = new RaiseIssueWorkRequestJPanel(userProcessContainer, userAccount, "Donation of Basic Amenities", system);
        userProcessContainer.add("rirwjp", rirwjp);
        cardLayout.next(userProcessContainer);
    }//GEN-LAST:event_btn_basicamenitiesActionPerformed

    private void btn_backpageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backpageActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btn_backpageActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_backpage;
    private javax.swing.JButton btn_basicamenities;
    private javax.swing.JButton btn_provideMedications;
    private javax.swing.JButton btn_treatment;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblHeader;
    // End of variables declaration//GEN-END:variables
}
